{
 "title": "Custom",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "bargauge",
     "description": "Resource pressure via PSI",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU"
      },
      {
       "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Mem"
      },
      {
       "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "I/O"
      },
      {
       "expr": "rate(node_pressure_irq_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Irq"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Overall CPU busy percentage (averaged across all cores)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$node\",job=\"$job\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Sys Load",
     "type": "gauge",
     "description": "System load over all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Real RAM usage excluding cache and reclaimable memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100, 0)"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Percentage of swap space currently used by the system",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} > bool 0) * ((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  (node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Breakdown",
     "type": "timeseries",
     "description": "CPU time spent busy vs idle, split by activity type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval]))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval]))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval]))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "avg(sum without(mode) (rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "avg(sum without (mode) (rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Breakdown",
     "type": "timeseries",
     "description": "RAM and swap usage overview, including caches",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Swap used"
      }
     ]
    },
    {
     "title": "Disk Usage Breakdown",
     "type": "timeseries",
     "description": "Percentage of filesystem space used for each mounted device",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~'rootfs'}) / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~'rootfs'}) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Per-interface network traffic (receive and transmit) in bits per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "Rx {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "Tx {{device}}"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "description": "Disk I/O throughput per device",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Network Traffic by Packets",
     "type": "timeseries",
     "description": "Number of network packets received and transmitted per second, by interface.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests/s",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({service_name=\"nginx\"}[5m]))"
      }
     ]
    },
    {
     "title": "HTTP Errors/s",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(\n  rate(\n    {service_name=\"nginx\"}\n    | json\n    | status =~ \"4..|5..\"\n    [5m]\n  )\n)"
      }
     ]
    },
    {
     "title": "HTTP Requests/s by Method",
     "type": "stat",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (method) (\n  rate(\n    {service_name=\"nginx\"}\n    | json\n    | method != \"\"\n    [5m]\n  )\n)"
      }
     ]
    },
    {
     "title": "Top 10 Requested URIs",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10,\n  sum by(uri) (\n    count_over_time({service_name=\"nginx\"} | json | __error__=\"\"[$__range])\n  )\n)"
      }
     ]
    },
    {
     "title": "Top Clients by Request Volume",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10,\n  sum by(remote_addr) (\n    count_over_time({service_name=\"nginx\"} | json | __error__=\"\"[5m])\n  )\n)"
      }
     ]
    },
    {
     "title": "HTTP Status Code Distribution",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(status) (\n  rate({service_name=\"nginx\"} | json | __error__=\"\"[5m])\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_calls_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transactions Committed per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (datname) (\n  rate(pg_stat_database_xact_commit{datname!~\"template.*|postgres\"}[5m])\n+\n  rate(pg_stat_database_xact_rollback{datname!~\"template.*|postgres\"}[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{state=\"active\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(pg_stat_statements_latency_max_exec_time)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(pg_stat_statements_latency_mean_exec_time)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"postgres\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  {
   "title": "SSH Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Logins",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"ssh\"}\n  |= \"sshd[\"\n  |~ \"Accepted (password|publickey) for\"\n  | __error__=\"\" [$__range]))"
      }
     ]
    },
    {
     "title": "Successful logins by IP",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 10, "x": 4, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (source_ip) (count_over_time({job=\"ssh\"}\n  |= \"sshd[\"\n  |~ \"Accepted (password|publickey) for\"\n  | regexp `sshd\\[(?P<pid>\\d+)\\]: Accepted (?P<auth_method>password|publickey) for (?P<user>\\S+) from (?P<source_ip>\\S+) port (?P<port>\\d+)`\n  | __error__=\"\" [$__range]))"
      }
     ]
    },
    {
     "title": "Failed attempts by IP",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (source_ip) (count_over_time({job=\"ssh\"}\n  |= \"sshd[\"\n  |~ \": Failed|: Invalid|: Connection closed by authenticating user\"\n  | regexp `(?:from|authenticating user \\S+) (?P<source_ip>\\S+) port`\n  | __error__=\"\" [$__range]))"
      }
     ]
    },
    {
     "title": "Failed Login Attempts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"ssh\"}\n  |= \"sshd[\"\n  |~ \": Failed|: Invalid\"\n  | __error__=\"\" [$__range]))"
      }
     ]
    },
    {
     "title": "Sessions Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 15 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"ssh\"}\n  |= \"sshd[\"\n  |~ \"Accepted (password|publickey) for\"\n  | regexp `sshd\\[(?P<pid>\\d+)\\]: Accepted (?P<auth_method>password|publickey) for (?P<user>\\S+) from (?P<source_ip>\\S+) port (?P<port>\\d+)`"
      },
      {
       "direction": "backward",
       "expr": "{job=\"ssh\"}\n  |= \"sshd[\"\n  |= \"session closed for user\"\n  | regexp `sshd\\[(?P<pid>\\d+)\\]: pam_unix\\(sshd:session\\): session closed for user (?P<user>\\S+)`"
      }
     ]
    },
    {
     "title": "Failed Logins Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"ssh\"}\n  |= \"sshd[\"\n  |= \"Failed password\"\n  | regexp `Failed password for (invalid user )?(?P<user>\\S+) from (?P<source_ip>\\S+) port (?P<port>\\d+)`"
      }
     ]
    }
   ]
  }
 ]
}